spring:
  datasource:
    driver-class-name: ${env.db.driver}
    url: jdbc:mysql://${env.db.ip}:${env.db.port}/${env.db.name}?characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: ${env.db.username}
    password: ${env.db.password}
#    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 10 #????????
      min-idle: 10 #???????
      max-active: 100 #?????
      max-wait: 10000 #????????????????????
      # druid????????
      stat-view-servlet:
        enabled: true #??druid??????????????
        url-pattern: /druid/*
        login-username: admin #druid??????
        login-password: caecaodb #druid??????

      web-stat-filter: #??????URI?????
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #?????????

      #??????????????druid???????filter???????????stat???SQL?????????sql?????
      filters: stat
      filter:
        slf4j:
          enabled: true
          statement-prepare-after-log-enabled: false #??1?create??
          statement-parameter-set-log-enabled: false #??2?????
          statement-execute-query-after-log-enabled: false #???1??????????sql???
          statement-execute-update-after-log-enabled: false #???1??????????sql???
          statement-execute-after-log-enabled: false #??????????????sql???
          statement-close-after-log-enabled: false #??1?closed??
          statement-create-after-log-enabled: false #??1?????created???
          statement-executable-sql-log-enable: true #????????????sql??????
          statement-sql-format-option:
            pretty-format: false #???sql????????3?
          statement-log-error-enabled: true
  profiles:
    active: dev
  application:
    name: game-recorder


logging:
  level:
    druid:
      sql:
        Statement: debug #???????druid???sql???S????
server:
  port: 28080
